// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZdP10dyCySWQ_gejejBPYbMKAUfyYxE',
    appId: '1:693999966425:android:8bbb1062f639ae7e1c86c8',
    messagingSenderId: '693999966425',
    projectId: 'watchplus-55d71',
    storageBucket: 'watchplus-55d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABxs4HAE77MkgsVFvu6Gy4c-LZk3Jb1TA',
    appId: '1:693999966425:ios:34001eecd8cadaec1c86c8',
    messagingSenderId: '693999966425',
    projectId: 'watchplus-55d71',
    storageBucket: 'watchplus-55d71.appspot.com',
    androidClientId: '693999966425-52b6ofjqua8ja7lsmsukp6pb3hdjtqok.apps.googleusercontent.com',
    iosClientId: '693999966425-in1joefnb9e51lvvhk468gfqsdv74h70.apps.googleusercontent.com',
    iosBundleId: 'com.shaderbytes.watchplus',
  );
}
